### ISSUE TITLE
Major change: + 3.15% IBAs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#32]
There are 119,342 new IBA annotations - I think this is the result of removing some overfiltering that took place during the emigration to Panther17. 

@dustine32 Can you please confirm?

**Comment by dustine32** [comment]
@pgaudet Correct! This number is very close to what we saw ([update stats](https://docs.google.com/spreadsheets/d/1NRIE5TpH5RuTmVIolrV1tuXReZTnOadIkR3S1ZssP2s/edit#gid=748162245)) after releasing the new PAINT IBA GAFs on 2023-04-10. This was due to recently adding back IBDs that were missed in the initial migration to PANTHER17.0 trees. More detail on this is in the GO wiki [here](https://wiki.geneontology.org/1_March_2023_PAINT_Conference_Call). I've also added a short note to the PAINT GAF release [README](http://data.pantherdb.org/ftp/downloads/paint/current/README).
